"""Data fixtures used within tests."""
POD_MINIMAL_FIXTURE = {
    "id": 12234,
    "name": None,
    "ppid": "PSL-123456",
    "payg": False,
    "home": True,
    "public": False,
    "evZone": False,
    "address_id": 1234,
    "description": "",
    "commissioned_at": "2022-01-25T09:00:00+00:00",
    "created_at": "2022-02-13T10:39:05+00:00",
    "last_contact_at": "2022-02-15T11:18:56+00:00",
    "contactless_enabled": False,
    "unit_id": 123456,
    "timezone": "UTC",
    "model": {
        "id": 123,
        "name": "S7-UC-03-ACA",
        "vendor": "Pod Point",
        "supports_payg": False,
        "supports_ocpp": False,
        "supports_contactless": False,
        "image_url": None,
    },
    "price": None,
    "statuses": [],
}

POD_COMPLETE_FIXTURE = {
    "id": 12234,
    "name": None,
    "ppid": "PSL-123456",
    "payg": False,
    "home": True,
    "public": False,
    "evZone": False,
    "location": {"lat": 0.12345, "lng": 2.45678901},
    "address_id": 1234,
    "description": "",
    "commissioned_at": "2022-01-25T09:00:00+00:00",
    "created_at": "2022-02-13T10:39:05+00:00",
    "last_contact_at": "2022-02-15T11:18:56+00:00",
    "contactless_enabled": False,
    "unit_id": 123456,
    "timezone": "UTC",
    "model": {
        "id": 123,
        "name": "S7-UC-03-ACA",
        "vendor": "Pod Point",
        "supports_payg": False,
        "supports_ocpp": False,
        "supports_contactless": False,
        "image_url": None,
    },
    "price": None,
    "statuses": [
        {
            "id": 2,
            "name": "Charging",
            "key_name": "charging",
            "label": "Charging",
            "door": "A",
            "door_id": 1,
        }
    ],
    "unit_connectors": [
        {
            "connector": {
                "id": 123,
                "door": "A",
                "door_id": 1,
                "power": 7,
                "current": 32,
                "voltage": 230,
                "charge_method": "Single Phase AC",
                "has_cable": False,
                "socket": {
                    "type": "IEC 62196-2 Type 2",
                    "description": "Type 2 socket",
                    "ocpp_name": "sType2",
                    "ocpp_code": 3,
                },
            }
        }
    ],
    "charge_schedules": [
        {
            "uid": "24b342c8-8cbb-11ec-1111-0a9268fc07a0",
            "start_day": 1,
            "start_time": "06:00:00",
            "end_day": 2,
            "end_time": "00:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24b8aeac-8cbb-11ec-2222-0a9268fc07a0",
            "start_day": 2,
            "start_time": "02:00:00",
            "end_day": 2,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24bb6606-8cbb-11ec-3333-0a9268fc07a0",
            "start_day": 3,
            "start_time": "02:00:00",
            "end_day": 3,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24be0168-8cbb-11ec-4444-0a9268fc07a0",
            "start_day": 4,
            "start_time": "02:00:00",
            "end_day": 4,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c089b0-8cbb-11ec-5555-0a9268fc07a0",
            "start_day": 5,
            "start_time": "02:00:00",
            "end_day": 5,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c346aa-8cbb-11ec-6666-0a9268fc07a0",
            "start_day": 6,
            "start_time": "02:00:00",
            "end_day": 6,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c6bf10-8cbb-11ec-7777-0a9268fc07a0",
            "start_day": 7,
            "start_time": "02:00:00",
            "end_day": 7,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
    ],
}

POD_COMPREHENSIVE_FIXTURE = {
    "id": 12234,
    "name": None,
    "ppid": "PSL-123456",
    "payg": False,
    "home": True,
    "public": False,
    "evZone": False,
    "location": {"lat": 0.12345, "lng": 2.45678901},
    "address_id": 1234,
    "description": "",
    "commissioned_at": "2022-01-25T09:00:00+00:00",
    "created_at": "2022-02-13T10:39:05+00:00",
    "last_contact_at": "2022-02-15T11:18:56+00:00",
    "contactless_enabled": False,
    "unit_id": 123456,
    "timezone": "UTC",
    "model": {
        "id": 123,
        "name": "S7-UC-03-ACA",
        "vendor": "Pod Point",
        "supports_payg": False,
        "supports_ocpp": False,
        "supports_contactless": False,
        "image_url": None,
    },
    "price": None,
    "statuses": [
        {
            "id": 2,
            "name": "Charging",
            "key_name": "charging",
            "label": "Charging",
            "door": "A",
            "door_id": 1,
        },
        {
            "id": 1,
            "name": "Available",
            "key_name": "available",
            "label": "Available",
            "door": "B",
            "door_id": 2,
        },
    ],
    "unit_connectors": [
        {
            "connector": {
                "id": 123,
                "door": "A",
                "door_id": 1,
                "power": 7,
                "current": 32,
                "voltage": 230,
                "charge_method": "Single Phase AC",
                "has_cable": False,
                "socket": {
                    "type": "IEC 62196-2 Type 2",
                    "description": "Type 2 socket",
                    "ocpp_name": "sType2",
                    "ocpp_code": 3,
                },
            }
        },
        {
            "connector": {
                "id": 234,
                "door": "B",
                "door_id": 2,
                "power": 7,
                "current": 32,
                "voltage": 230,
                "charge_method": "Single Phase AC",
                "has_cable": False,
                "socket": {
                    "type": "IEC 62196-2 Type 2",
                    "description": "Type 2 socket",
                    "ocpp_name": "sType2",
                    "ocpp_code": 3,
                },
            }
        },
    ],
    "charge_schedules": [
        {
            "uid": "24b342c8-8cbb-11ec-1111-0a9268fc07a0",
            "start_day": 1,
            "start_time": "06:00:00",
            "end_day": 2,
            "end_time": "00:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24b8aeac-8cbb-11ec-2222-0a9268fc07a0",
            "start_day": 2,
            "start_time": "02:00:00",
            "end_day": 2,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24bb6606-8cbb-11ec-3333-0a9268fc07a0",
            "start_day": 3,
            "start_time": "02:00:00",
            "end_day": 3,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24be0168-8cbb-11ec-4444-0a9268fc07a0",
            "start_day": 4,
            "start_time": "02:00:00",
            "end_day": 4,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c089b0-8cbb-11ec-5555-0a9268fc07a0",
            "start_day": 5,
            "start_time": "02:00:00",
            "end_day": 5,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c346aa-8cbb-11ec-6666-0a9268fc07a0",
            "start_day": 6,
            "start_time": "02:00:00",
            "end_day": 6,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
        {
            "uid": "24c6bf10-8cbb-11ec-7777-0a9268fc07a0",
            "start_day": 7,
            "start_time": "02:00:00",
            "end_day": 7,
            "end_time": "07:00:00",
            "status": {"is_active": False},
        },
    ],
}
