default_config:

logger:
  default: info
  logs:
    custom_components.pod_point: debug
    podpointclient: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:

dhcp:

discovery: