set_charge_mode:
  name: Set charge mode
  description: Set the charge mode for a pod

  target:
    entity:
      domain: pod_point
      # supported_features:
      #   - pod_point.PodPointEntity.SET_CHARGE_MODE
  fields:
    name: Charge mode
    description: Charge mode to set
    required: True
    example: "smart"
    default: "manual"
    selector:
      select:
        options:
          - "smart"
          - "manual"
